#include "config.h"
#include "commands.h" // For SendToAndroid
#include <stdio.h>     // For sscanf
#include "stm32f1xx_hal.h" // Include the HAL *here* for flash operations

// --- Configuration Variables (Defaults) ---
uint32_t config_ign_src = IGNITION_STATUS_ID;
uint32_t config_illum_src = DASHBOARD_LIGHTS_ID;
uint32_t config_rev_src = REVERSE_GEAR_ID;
uint32_t config_park_src = DASHBOARD_LIGHTS_ID;
uint32_t config_door_src = DOOR_STATUS_ID;

// --- Flash Storage (STM32F103 Specific) ---

// *IMPORTANT*:  Choose an address that is *outside* of your program code!
//  On the STM32F103C8, the flash starts at 0x08000000.  The program code
//  will typically occupy the first part of flash.  You need to choose an
//  address that's far enough along to avoid overwriting your program.
//  0x0800F000 is likely safe for smaller programs, but *check your .map file*!
//  The .map file (generated by the linker) shows the memory layout of your
//  program.  Look for the end address of your code.
#define CONFIG_FLASH_ADDRESS 0x0800F000

//  The STM32F103 has 1KB or 2KB pages (depending on the density).  We *must* erase
//  an entire page before writing.  We'll use a single page for our configuration.
#define CONFIG_PAGE_SIZE 1024 // Or 2048, depending on your chip.  Check datasheet!

//  "Magic Number" to check if flash has been initialized.  Choose any unique value.
#define CONFIG_MAGIC_NUMBER 0xCAFEBABE

// Structure to hold our configuration data.  This makes it easier to
//  read and write the data as a block.
typedef struct {
    uint32_t magic_number;
    uint32_t ign_src;
    uint32_t illum_src;
    uint32_t rev_src;
    uint32_t park_src;
    uint32_t door_src;
} ConfigData;


void load_config(void) {
    ConfigData *config = (ConfigData *)CONFIG_FLASH_ADDRESS;

    if (config->magic_number == CONFIG_MAGIC_NUMBER) {
        // Valid configuration data found.  Load it.
        config_ign_src = config->ign_src;
        config_illum_src = config->illum_src;
        config_rev_src = config->rev_src;
        config_park_src = config->park_src;
        config_door_src = config->door_src;
    } // Else:  Use default values (already initialized above).
}
void save_config(void) {

    ConfigData config;

    config.magic_number = CONFIG_MAGIC_NUMBER;
    config.ign_src = config_ign_src;
    config.illum_src = config_illum_src;
    config.rev_src = config_rev_src;
    config.park_src = config_park_src;
    config.door_src = config_door_src;

    HAL_FLASH_Unlock();

    // Erase the configuration page.
    FLASH_EraseInitTypeDef erase_init;
    erase_init.TypeErase = FLASH_TYPEERASE_PAGES;
    erase_init.PageAddress = CONFIG_FLASH_ADDRESS;
    erase_init.NbPages = 1; // Erase a single page
    uint32_t page_error = 0; // Variable to hold error information

    if (HAL_FLASHEx_Erase(&erase_init, &page_error) != HAL_OK) {
        // Handle erase error.  Could be a flash protection issue,
        //  or an invalid address.
        SendToAndroid(RESP_ERR, "FLASH_ERASE_ERR");
		HAL_FLASH_Lock(); //Always lock the flash after operation
        return;
    }

    // Program the configuration data.  We write it as a struct.
	uint8_t * pData = (uint8_t *)&config;
	for(int i = 0; i < sizeof(ConfigData); i+=4){
		if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, CONFIG_FLASH_ADDRESS + i, *(uint32_t *)(pData + i)) != HAL_OK) {
       		 // Handle program error.
        	SendToAndroid(RESP_ERR, "FLASH_WRITE_ERR");
			HAL_FLASH_Lock(); //Always lock the flash after operation
        	return;
		}
	}
    HAL_FLASH_Lock();
}

void ProcessConfigCommand(const char *parameter, const char *value) {
 // ... (Rest of ProcessConfigCommand - No Changes, see previous response) ...
  if (strcmp(parameter, "GET") == 0) {
        if (strcmp(value, "ign_src") == 0) {
            char buf[32];
            snprintf(buf, sizeof(buf), "ign_src:%#x", (unsigned int)config_ign_src);
            SendToAndroid(RESP_CFG, buf);
        } else if (strcmp(value, "illum_src") == 0) {
            char buf[32];
            snprintf(buf, sizeof(buf), "illum_src:%#x", (unsigned int)config_illum_src);
            SendToAndroid(RESP_CFG, buf);
        } else if (strcmp(value, "rev_src") == 0) {
            char buf[32];
            snprintf(buf, sizeof(buf), "rev_src:%#x", (unsigned int)config_rev_src);
            SendToAndroid(RESP_CFG, buf);
        } else if (strcmp(value, "park_src") == 0) {
            char buf[32];
            snprintf(buf, sizeof(buf), "park_src:%#x", (unsigned int)config_park_src);
            SendToAndroid(RESP_CFG, buf);
        } else if(strcmp(value, "door_src") == 0) {
             char buf[32];
            snprintf(buf, sizeof(buf), "door_src:%#x", (unsigned int)config_door_src);
            SendToAndroid(RESP_CFG, buf);
        }
        // Add other configuration parameters as needed
        else {
            SendToAndroid(RESP_ERR, ERR_INVALID_CONFIG);
        }
    } else if (strcmp(parameter, "SET") == 0) {
        // Convert the value string to a uint32_t
        unsigned int new_value;
        if (sscanf(value, "%x", &new_value) == 1) { // Use %x for hex input
            if (strcmp(value, "ign_src") == 0) {
                config_ign_src = (uint32_t)new_value;
				save_config();
            } else if(strcmp(value, "illum_src") == 0) {
                config_illum_src = (uint32_t)new_value;
				save_config();
            } else if(strcmp(value, "rev_src") == 0){
                config_rev_src = (uint32_t)new_value;
				save_config();
            } else if(strcmp(value, "park_src") == 0){
                config_park_src = (uint32_t)new_value;
				save_config();
            } else if (strcmp(value, "door_src") == 0){
                config_door_src = (uint32_t)new_value;
				save_config();
            }
            // Add other configuration parameters
            else {
                SendToAndroid(RESP_ERR, ERR_INVALID_CONFIG);
            }
        } else {
            SendToAndroid(RESP_ERR, ERR_INVALID_CONFIG); // Invalid value format
        }
    } else {
        SendToAndroid(RESP_ERR, ERR_INVALID_CONFIG); // Invalid parameter (not GET or SET)
    }
}
